config/routes.rb
Rails.application.routes.draw do

  root                  'pages#home'
  get 'about',      to: 'pages#about'
  get 'academics',  to: 'pages#academics'
  get 'admissions', to: 'pages#admissions'
  get 'courses',    to: 'pages#courses'
  get 'contact',    to: 'pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
  end

  def about
  end

  def academics
  end

  def admissions
  end

  def courses
  end

  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "English Learning Centre Instant Tutor"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/academics.html.erb
<% provide(:title, "Help") %>
<%= render 'shared/header_no_image' %>
	<!--start-academics-->
	<div class="admission">
		<div class="container">
			<div class="admi-top">
				<h3>Academics</h3>
				<div class="admi-main">
					<div class="col-md-7 admi-main-left">
						<p>Integer hendrerit malesuada lorem, ac eleifend arcu scelerisque nec. Integer tempus posuere nunc. Duis vel ligula ullamcorper, cursus ipsum sed, tristique sem. Aliquam sodales iaculis tincidunt. Nulla bibendum, risus tincidunt euismod tempus, leo ipsum elementum mauris, ac dignissim leo libero eget augue. Phasellus dapibus gravida leo, in convallis ante iaculis quis. Donec sodales ligula elit, ac sollicitudin ante dictum ac. Phasellus iaculis condimentum dui. Donec a tincidunt nunc. Suspendisse in sodales nunc. Ut sollicitudin viverra risus, varius elementum risus.</p>
					</div>
					<%= render 'shared/announcements' %>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="admin-bottom">
				<div class="col-md-3 admin-bottom-left">
					<h4>Student's Area</h4>
					<ul>
						<li><a href="#">Student Profile</a></li>
						<li><a href="#">Time Table</a></li>
						<li><a href="#">Forms Download</a></li>
						<li><a href="#">Extra Class Form</a></li>
						<li><a href="#">Exam Seating Plan</a></li>
					</ul>
				</div>
				<div class="col-md-3 admin-bottom-left">
					<h4>Departments</h4>
					<ul>
						<li><a href="#">Computer Engineering</a></li>
						<li><a href="#">Soft Engineering</a></li>
						<li><a href="#">Management Science</a></li>
						<li><a href="#">Earth & Environmental Science</a></li>
						<li><a href="#">Computer Science</a></li>
						<li><a href="#">Information Technology</a></li>
						<li><a href="#">Electrical Engineering</a></li>
					</ul>
				</div>
				<div class="col-md-3 admin-bottom-left">
					<h4>Faculty Services</h4>
					<ul>
						<li><a href="#">Attendance System</a></li>
						<li><a href="#">Employee Profile</a></li>
						<li><a href="#">Employee Profile-Visiting Faculty</a></li>
					</ul>
				</div>
				<div class="col-md-3 admin-bottom-left">
					<h4>e-services</h4>
					<ul>
						<li><a href="#">e-classes</a></li>
						<li><a href="#">e-admission</a></li>
						<li><a href="#">e-alumni</a></li>
						<li><a href="#">e-mail</a></li>
						<li><a href="#">e-library</a></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--end-admissions-->
	<!--Slider-Starts-Here-->
			<script src="js/responsiveslides.min.js"></script>
			 <script>
			    // You can also use "$(window).load(function() {"
			    $(function () {
			      // Slideshow 4
			      $("#slider4").responsiveSlides({
			        auto: true,
			        pager: true,
			        nav: true,
			        speed: 500,
			        namespace: "callbacks",
			        before: function () {
			          $('.events').append("<li>before event fired.</li>");
			        },
			        after: function () {
			          $('.events').append("<li>after event fired.</li>");
			        }
			      });
			
			    });
			  </script>
			<!--End-slider-script-->
	<!--end-academics-->
	<%= render 'shared/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title)) %></title>
<meta name="viewport" content="width=device-width, initial-scale=1">	
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<meta name="keywords" content="Bootstrap Responsive Templates, Iphone Compatible Templates, Smartphone Compatible Templates, Ipad Compatible Templates, Flat Responsive Templates"/>
<%= stylesheet_link_tag 'application', media: 'all',
						'data-turbolinks-track' => true %>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>  
<script src="js/jquery.min.js"></script>
<!---- start-smoth-scrolling---->
<script type="text/javascript" src="js/move-top.js"></script>
<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){		
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
				});
			});
		</script>

<!---- start-smoth-scrolling---->
<script type="text/javascript" src="js/jquery.mousewheel.js"></script>
<script type="text/javascript" src="js/jquery.contentcarousel.js"></script>
<script type="text/javascript" src="js/easing.js"></script>
<%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
	<%= render 'shared/header' %>
	<!--start-about-->
	<div class="about">
		<div class="container">
			<div class="about-main">
				<h3>A Few Words About Us</h3>
				<h5>Uspendisse laoreet nibh ac cursus vestibulum. Vestibulum eu arcu at justo tristique malesuada. Aliquam erat volutpat. Vivamus condimentum feugiat magna</h5>
				<p>Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. Maecenas tristique orc i ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor, dapibus eget, elementum vel, cursus eleifend, elit. Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Integer rutrum ante eu lacus.</p>
				<div class="about-text">
					<div class="col-md-4 about-text-left">
						<img src="images/st-1.jpg" alt="">
						<h5>What We Do</h5>
						<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam et dignissim augue, et sagittis turpis. Vestibulum congue turpis ac tincidunt accumsan.</p>
						<div class="tool">
							<a class="tooltips" href="#">
							<span>Read More</span></a>
						</div>
					</div>
					<div class="col-md-4 about-text-left">
						<img src="images/st-2.jpg" alt="">
						<h5>Our Capabilities</h5>
						<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam et dignissim augue, et sagittis turpis. Vestibulum congue turpis ac tincidunt accumsan.</p>
						<div class="tool">
							<a class="tooltips" href="#">
							<span>Read More</span></a>
						</div>
					</div>
					<div class="col-md-4 about-text-left">
						<img src="images/st-4.jpg" alt="">
						<h5>Our Standards</h5>
						<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam et dignissim augue, et sagittis turpis. Vestibulum congue turpis ac tincidunt accumsan.</p>
						<div class="tool">
							<a class="tooltips" href="#">
							<span>Read More</span></a>
						</div>
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
		</div>
	</div>
	<!--end-about-->
	<%= render 'shared/vision' %>
	<%= render 'shared/footer' %>

app/views/pages/academics.html.erb
<% provide(:title, "Help") %>
<%= render 'shared/header' %>
	<!--start-academics-->
	<div class="admission">
		<div class="container">
			<div class="admi-top">
				<h3>Academics</h3>
				<div class="admi-main">
					<div class="col-md-7 admi-main-left">
						<p>Integer hendrerit malesuada lorem, ac eleifend arcu scelerisque nec. Integer tempus posuere nunc. Duis vel ligula ullamcorper, cursus ipsum sed, tristique sem. Aliquam sodales iaculis tincidunt. Nulla bibendum, risus tincidunt euismod tempus, leo ipsum elementum mauris, ac dignissim leo libero eget augue. Phasellus dapibus gravida leo, in convallis ante iaculis quis. Donec sodales ligula elit, ac sollicitudin ante dictum ac. Phasellus iaculis condimentum dui. Donec a tincidunt nunc. Suspendisse in sodales nunc. Ut sollicitudin viverra risus, varius elementum risus.</p>
					</div>
					<%= render 'shared/announcements' %>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="admin-bottom">
				<div class="col-md-3 admin-bottom-left">
					<h4>Student's Area</h4>
					<ul>
						<li><a href="#">Student Profile</a></li>
						<li><a href="#">Time Table</a></li>
						<li><a href="#">Forms Download</a></li>
						<li><a href="#">Extra Class Form</a></li>
						<li><a href="#">Exam Seating Plan</a></li>
					</ul>
				</div>
				<div class="col-md-3 admin-bottom-left">
					<h4>Departments</h4>
					<ul>
						<li><a href="#">Computer Engineering</a></li>
						<li><a href="#">Soft Engineering</a></li>
						<li><a href="#">Management Science</a></li>
						<li><a href="#">Earth & Environmental Science</a></li>
						<li><a href="#">Computer Science</a></li>
						<li><a href="#">Information Technology</a></li>
						<li><a href="#">Electrical Engineering</a></li>
					</ul>
				</div>
				<div class="col-md-3 admin-bottom-left">
					<h4>Faculty Services</h4>
					<ul>
						<li><a href="#">Attendance System</a></li>
						<li><a href="#">Employee Profile</a></li>
						<li><a href="#">Employee Profile-Visiting Faculty</a></li>
					</ul>
				</div>
				<div class="col-md-3 admin-bottom-left">
					<h4>e-services</h4>
					<ul>
						<li><a href="#">e-classes</a></li>
						<li><a href="#">e-admission</a></li>
						<li><a href="#">e-alumni</a></li>
						<li><a href="#">e-mail</a></li>
						<li><a href="#">e-library</a></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--end-admissions-->
	<!--Slider-Starts-Here-->
			<% javascript_path  "min" %>
			 <script>
			    // You can also use "$(window).load(function() {"
			    $(function () {
			      // Slideshow 4
			      $("#slider4").responsiveSlides({
			        auto: true,
			        pager: true,
			        nav: true,
			        speed: 500,
			        namespace: "callbacks",
			        before: function () {
			          $('.events').append("<li>before event fired.</li>");
			        },
			        after: function () {
			          $('.events').append("<li>after event fired.</li>");
			        }
			      });
			
			    });
			  </script>
			<!--End-slider-script-->
	<!--end-academics-->
	<%= render 'shared/footer' %>

app/views/pages/admissions.html.erb
<% provide(:title, "Admissions") %>
<%= render 'shared/header' %>
	<!--start-admissions-->
	<div class="admission">
		<div class="container">
			<div class="admi-top">
				<h3>Admissions</h3>
				<div class="admi-main">
					<div class="col-md-7 admi-main-left">
						<div  id="top" class="callbacks_container">
			      		<ul class="rslides" id="slider4">
			        	<li>
								<img src="images/admi-1.jpg" alt="">
						</li>
						<li>
							<img src="images/admi-2.jpg" alt="">
						</li>
						<li>
							<img src="images/admi-3.jpg" alt="">
						</li>
			      </ul>
			    </div>
			    <div class="clearfix"> </div>
					</div>
					<%= render 'shared/announcements' %>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="admin-bottom">
				<div class="col-md-3 admin-bottom-left">
					<h4>Student's Area</h4>
					<ul>
						<li><a href="#">Student Profile</a></li>
						<li><a href="#">Time Table</a></li>
						<li><a href="#">Forms Download</a></li>
						<li><a href="#">Extra Class Form</a></li>
						<li><a href="#">Exam Seating Plan</a></li>
					</ul>
				</div>
				<div class="col-md-3 admin-bottom-left">
					<h4>Departments</h4>
					<ul>
						<li><a href="#">Computer Engineering</a></li>
						<li><a href="#">Soft Engineering</a></li>
						<li><a href="#">Management Science</a></li>
						<li><a href="#">Earth & Environmental Science</a></li>
						<li><a href="#">Computer Science</a></li>
						<li><a href="#">Information Technology</a></li>
						<li><a href="#">Electrical Engineering</a></li>
					</ul>
				</div>
				<div class="col-md-3 admin-bottom-left">
					<h4>Faculty Services</h4>
					<ul>
						<li><a href="#">Attendance System</a></li>
						<li><a href="#">Employee Profile</a></li>
						<li><a href="#">Employee Profile-Visiting Faculty</a></li>
					</ul>
				</div>
				<div class="col-md-3 admin-bottom-left">
					<h4>e-services</h4>
					<ul>
						<li><a href="#">e-classes</a></li>
						<li><a href="#">e-admission</a></li>
						<li><a href="#">e-alumni</a></li>
						<li><a href="#">e-mail</a></li>
						<li><a href="#">e-library</a></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--end-admissions-->
	<!--Slider-Starts-Here-->
			<script src="js/responsiveslides.min.js"></script>
			 <script>
			    // You can also use "$(window).load(function() {"
			    $(function () {
			      // Slideshow 4
			      $("#slider4").responsiveSlides({
			        auto: true,
			        pager: true,
			        nav: true,
			        speed: 500,
			        namespace: "callbacks",
			        before: function () {
			          $('.events').append("<li>before event fired.</li>");
			        },
			        after: function () {
			          $('.events').append("<li>after event fired.</li>");
			        }
			      });
			
			    });
			  </script>
			<!--End-slider-script-->
	<%= render 'shared/footer' %>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<%= render 'shared/header' %>
	<!--start-contact-->
	<div class="contact">
		<div class="container">
			<div class="contact-top">
				<h3>Contact Us</h3>
				<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3745.657945920633!2d94.925709!3d20.148312999999998!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30b7d19881308ae9%3A0x229dbaae31b864b9!2sZarmani!5e0!3m2!1sen!2sin!4v1419654909172" frameborder="0" style="border:0"></iframe>
			</div>
			<div class="contact-bottom">
				<div class="col-md-5 contact-left">
					<h4>Contact Info</h4>
					<div class="c-bottom">
						<div class="c-l-left">
							<span class="address"> </span>
						</div>
						<div class="c-l-right">
							<h6>The Company Name agi.
					<span>756 gt globel Place,</span>
						CD-Road,M 07 435.
					</h6>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="c-bottom">
						<div class="c-l-left">
							<span class="phone"> </span>
						</div>
						<div class="c-l-right">
							<p>Telephone: +1 234 567 9871
								<span>FAX: +1 234 567 9871</span>
							</p>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="c-bottom">
						<div class="c-l-left">
							<span class="mail"> </span>
						</div>
						<div class="c-l-right">
							<p><a href="mailto:info@example.com">mail@user.com</a></p>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="col-md-7 contact-left">
					<h4>Contact Form</h4>
					<div class="contact-text">
						<input type="text" value="First Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'First Name';}"/>
						<input type="text" value="Second Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Second Name';}"/>
						<input type="text" value="Email Id" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email Id';}"/>
					</div>
					<div class="contact-textarea">
						<textarea value="Message:" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message';}">Message..</textarea>
					</div>
					<div class="contact-but">
						<input type="submit" />
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!--end-contact-->
	<%= render 'shared/footer' %>

app/views/pages/courses.html.erb
<% provide(:title, "Courses") %>
<!---- start-smoth-scrolling---->
<script type="text/javascript" src="js/jquery.mixitup.min.js"></script>
<script type="text/javascript">
$(function () {
	
	var filterList = {
	
		init: function () {
		
			// MixItUp plugin
			// http://mixitup.io
			$('#portfoliolist').mixitup({
				targetSelector: '.portfolio',
				filterSelector: '.filter',
				effects: ['fade'],
				easing: 'snap',
				// call the hover effect
				onMixEnd: filterList.hoverEffect()
			});				
		
		},
		
		hoverEffect: function () {
		
			// Simple parallax effect
			$('#portfoliolist .portfolio').hover(
				function () {
					$(this).find('.label').stop().animate({bottom: 0}, 200, 'easeOutQuad');
					$(this).find('img').stop().animate({top: -30}, 500, 'easeOutQuad');				
				},
				function () {
					$(this).find('.label').stop().animate({bottom: -40}, 200, 'easeInQuad');
					$(this).find('img').stop().animate({top: 0}, 300, 'easeOutQuad');								
				}		
			);				
		
		}

	};
	
	// Run the show!
	filterList.init();
	
	
});	
</script>
</head>
<%= render 'shared/header' %>
<%= render 'shared/portfolio' %>
<%= render 'shared/footer' %>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
	<%= render 'shared/header' %>
	<%= render 'shared/welcome' %>
	<%= render 'shared/news' %>
	<div class="staff">
		<div class="container">
			<div class="staff-text">
				<h3>Our staff</h3>
				<div class="staff-main">
					<div class="col-md-5 staff-main-left">
						<h5>Uspendisse laoreet nibh ac cursus vestibulum. Vestibulum eu arcu at justo tristique malesuada.</h5>
						<P>Aenean ac urna ut neque semper maximus at et ligula. Aliquamex risus, pretiu sed pharetra efficitur sit amet ligula. urna ut neque semper maximus at et ligula urna ut neque</P>
						<h4>Pofessor Details</h4>
						<h5 class="s1">Shane mack</h5>
						<p>Aenean ac urna ut neque semper maximus at et ligula. Aliquamex risus, pretiu sed pharetra efficitur sit amet ligula. </p>
						<h5 class="s1">Marry jain</h5>
						<p>Aenean ac urna ut neque semper maximus at et ligula. Aliquamex risus, pretiu sed pharetra efficitur sit amet ligula. </p>
						<div class="tool">
						<a class="tooltips" href="#">
							<span>Read More</span></a>
						</div>
					</div>
					<div class="col-md-7 events-col">
				<div id="ca-container" class="ca-container"><div class="ca-nav"><span class="ca-nav-prev">Previous</span><span class="ca-nav-next">Next</span></div>
				    <div class="ca-wrapper" style="overflow: hidden;">
				         
						<div class="ca-item ca-item-2" style="position: absolute; left: 0px;">
							<div class="ca-item-main">
								<div class="ca-icon">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div>  
								</div>
								<div class="ca-icon2">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div> 
								 </div>
							</div>
						</div>
						<div class="ca-item ca-item-3" style="position: absolute; left: 225px;">
							<div class="ca-item-main">
								<div class="ca-icon">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div> 
								 </div>
								<div class="ca-icon3">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div> 
								 </div>
							</div>
						</div>
						<div class="ca-item ca-item-4" style="position: absolute; left: 450px;">
							<div class="ca-item-main">
								<div class="ca-icon"> 
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div> 	
								</div>
								<div class="ca-icon4">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div> 
							  	</div>
						     </div>
						</div>
						<div class="ca-item ca-item-5" style="position: absolute; left: 675px;">
							<div class="ca-item-main">
								<div class="ca-icon">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div> 
								 </div>
								<div class="ca-icon5">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div> 
								 </div>
							</div>
						</div>
						<div class="ca-item ca-item-6" style="position: absolute; left: 900px;">
							<div class="ca-item-main">
								<div class="ca-icon">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div>  
								</div>
								<div class="ca-icon6">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div>  
								</div>
							</div>
						</div>
						<div class="ca-item ca-item-7" style="position: absolute; left: 1125px;">
							<div class="ca-item-main">
								<div class="ca-icon">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div>  
								</div>
								<div class="ca-icon7">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div> 
								 </div>
							</div>
						</div>
						<div class="ca-item ca-item-8" style="position: absolute; left: 1350px;">
							<div class="ca-item-main">
								<div class="ca-icon">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div>  
								</div>
								<div class="ca-icon">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div>  
								</div>
							</div>
						</div>
			    <div class="ca-item ca-item-1" style="position: absolute; left: 1575px;">
						   <div class="ca-item-main">
								<div class="ca-icon">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div> 
								</div>
								<div class="ca-icon1">
									<div class="caption">
										<p>Marry &amp; jain<br>professor</p>
									</div> 
								 </div>
							</div>
						  </div></div>
					<script type="text/javascript">
			$('#ca-container').contentcarousel();
		</script>
			</div>
		</div>
   					<div class="clearfix"> </div>
					</div>
				</div>
			</div>
		</div>
	<%= render 'shared/footer' %>

app/views/shared/_announcements.html.erb
<div class="col-md-5 admi-main-right">
						<h4>Announcements</h4>
						<div class="admi-right">
							<div class="admi-right-left">
								<h5>1</h5>
							</div>
							<div class="admi-right-right">
								<h6>Nunc ultrices rhoncus consequat</h6>
								<p>Nov  29,2013</p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="admi-right">
							<div class="admi-right-left">
								<h5>2</h5>
							</div>
							<div class="admi-right-right">
								<h6>Sed varius tincidunt est</h6>
								<p>oct  23,2013</p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="admi-right">
							<div class="admi-right-left">
								<h5>3</h5>
							</div>
							<div class="admi-right-right">
								<h6>Phasellus posuere tempor enim</h6>
								<p>dec  18,2013</p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="admi-right">
							<div class="admi-right-left">
								<h5>4</h5>
							</div>
							<div class="admi-right-right">
								<h6>Maecenas in blandit neque</h6>
								<p>mar  13,2013</p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="admi-right">
							<div class="admi-right-left">
								<h5>5</h5>
							</div>
							<div class="admi-right-right">
								<h6>Curabitur vestibulum erat quis</h6>
								<p>jan  3,2013</p>
							</div>
							<div class="clearfix"></div>
						</div>
					</div>

app/views/shared/_header.html.erb
	<div class="banner" id="home">
		<div class="container">
			<div class="header">
				<div class="menu">
                                     <a class="toggleMenu" href="#"><img src="images/menu-icon.png" alt="" /> </a>
					<ul class="nav" id="nav">
					<li><%= link_to 'Home', 	  root_path %></li>
					<li><%= link_to 'About', 	  about_path %></li>
					<li><%= link_to 'Academics',  academics_path %></li>
					<li><%= link_to 'Admissions', admissions_path %></li>
					<li><%= link_to 'Courses',    courses_path %></li>
					<li><%= link_to 'Contact', 	  contact_path %></li>
					</ul>
                                  <!----start-top-nav-script---->
		                      <script type="text/javascript" src="js/responsive-nav.js"></script>
					<script type="text/javascript">
					jQuery(document).ready(function($) {
						$(".scroll").click(function(event){		
							event.preventDefault();
							$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
						});
					});
					</script>
		<!----//End-top-nav-script---->
				</div>
				<div class="clearfix"> </div>
			</div>
			<%= render 'shared/text_slider' %>
		</div>
	</div>

	

app/views/shared/_header_no_image.html.erb
<div class="banner1" id="home">
		<div class="container">
			<div class="header">
				<div class="menu">
                                     <a class="toggleMenu" href="#"><img src="images/menu-icon.png" alt="" /> </a>
					<ul class="nav" id="nav">
					<li><%= link_to 'Home', 	  root_path %></li>
					<li><%= link_to 'About', 	  about_path %></li>
					<li><%= link_to 'Academics',  academics_path %></li>
					<li><%= link_to 'Admissions', admissions_path %></li>
					<li><%= link_to 'Courses',    courses_path %></li>
					<li><%= link_to 'Contact', 	  contact_path %></li>
					</ul>
                                  <!----start-top-nav-script---->
		                      <script type="text/javascript" src="js/responsive-nav.js"></script>
					<script type="text/javascript">
					jQuery(document).ready(function($) {
						$(".scroll").click(function(event){		
							event.preventDefault();
							$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
						});
					});
					</script>
		<!----//End-top-nav-script---->
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>